"""
cookie_manager.py — Single owner of all cookie I/O.

All cookie read/write/delete operations go through this module.
No other file should directly touch cookies.txt or the cookies/ directory.
"""
import os
import shutil
from datetime import datetime
from config import COOKIE_FILE, COOKIES_DIR


def exists():
    """Check if the active cookie file exists and is non-empty."""
    return os.path.isfile(COOKIE_FILE) and os.path.getsize(COOKIE_FILE) > 0


def get_path():
    """Returns the absolute path to the active cookie file."""
    return COOKIE_FILE


def read_netscape():
    """Parse the active Netscape-format cookie file and return a list of cookie dicts."""
    cookies = []
    if not os.path.exists(COOKIE_FILE):
        return cookies
    with open(COOKIE_FILE, 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            parts = line.strip().split('\t')
            if len(parts) >= 7:
                cookies.append({
                    'name': parts[5],
                    'value': parts[6],
                    'domain': parts[0],
                    'path': parts[2],
                    'secure': parts[3] == 'TRUE',
                    'expires': float(parts[4]) if parts[4] != '0' else -1
                })
    return cookies


def write_netscape(cookies_list, source="unknown"):
    """
    Write cookies to the active cookie file in Netscape format.
    `cookies_list` is a list of SimpleCookie objects from pywebview.
    Returns the number of cookies written.
    """
    cookie_count = 0
    with open(COOKIE_FILE, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n")
        f.write(f"# Generated by Tikkocampus ({source})\n\n")

        for cookie_obj in cookies_list:
            for name, morsel in cookie_obj.items():
                domain = morsel.get("domain", "")
                include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
                path = morsel.get("path", "/")
                secure = "TRUE" if morsel.get("secure", False) else "FALSE"
                expires = "0"
                value = morsel.value

                f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
                cookie_count += 1

    return cookie_count


def delete():
    """Delete the active cookie file."""
    if os.path.exists(COOKIE_FILE):
        os.remove(COOKIE_FILE)


def copy_to_history():
    """Copy the active cookie file to the history directory with a timestamped name."""
    if not os.path.exists(COOKIE_FILE):
        return None
    os.makedirs(COOKIES_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_filename = f"cookie_{timestamp}.txt"
    dest = os.path.join(COOKIES_DIR, unique_filename)
    shutil.copyfile(COOKIE_FILE, dest)
    enforce_limit()
    return unique_filename


def select_from_history(filename):
    """Set a historical cookie file as the active cookie file."""
    source_path = os.path.join(COOKIES_DIR, filename)
    if not os.path.exists(source_path):
        raise FileNotFoundError(f"Cookie file not found: {filename}")
    shutil.copyfile(source_path, COOKIE_FILE)


def save_uploaded(file_obj):
    """Save an uploaded file to history and set it as active. Returns the filename."""
    os.makedirs(COOKIES_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_filename = f"cookie_{timestamp}.txt"
    save_path = os.path.join(COOKIES_DIR, unique_filename)

    with open(save_path, "wb") as buffer:
        shutil.copyfileobj(file_obj, buffer)

    # Set as active
    shutil.copyfile(save_path, COOKIE_FILE)
    enforce_limit()
    return unique_filename


def list_history():
    """Returns a sorted list of historical cookie files (newest first)."""
    enforce_limit()
    cookies = []
    if not os.path.exists(COOKIES_DIR):
        return cookies

    for filename in os.listdir(COOKIES_DIR):
        if filename.endswith(".txt"):
            file_path = os.path.join(COOKIES_DIR, filename)
            mtime = os.path.getmtime(file_path)
            created_str = datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S")
            cookies.append({
                "filename": filename,
                "created_at": created_str,
                "timestamp": mtime
            })
    cookies.sort(key=lambda x: x["timestamp"], reverse=True)
    return cookies


def delete_from_history(filename):
    """Delete a specific historical cookie file."""
    file_path = os.path.join(COOKIES_DIR, filename)
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Cookie file not found: {filename}")
    os.remove(file_path)


def enforce_limit(max_files=4):
    """Ensures there are never more than max_files cookie files in the history directory."""
    if not os.path.exists(COOKIES_DIR):
        return

    files = [f for f in os.listdir(COOKIES_DIR) if f.endswith(".txt")]
    if len(files) <= max_files:
        return

    file_paths = [os.path.join(COOKIES_DIR, f) for f in files]
    file_paths.sort(key=os.path.getmtime, reverse=True)

    for old_path in file_paths[max_files:]:
        try:
            os.remove(old_path)
        except Exception:
            pass
